name: kkaebom
description: 유기견 봉사활동 서비스
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.9.0
  firebase_analytics: ^10.2.0
  firebase_crashlytics: ^3.1.0
  provider: ^6.0.5
  flutter_svg: ^2.0.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  drift: ^2.7.0
  sqlite3_flutter_libs: ^0.5.13
  path_provider: ^2.0.14
  path: ^1.8.2
  firebase_remote_config: ^4.0.0
  dynamic_color: ^1.6.3
  get_it: ^7.2.0
  event_hub: ^0.2.1
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  drift_dev: ^2.7.0

flutter:
  uses-material-design: true
#   assets:
#     - images/a_dot_burr.jpeg
#     - images/a_dot_ham.jpeg
